const vocabulary = [
  { chinese: "爱", pinyin: "ài", meaning: "รัก" },
  { chinese: "爱好", pinyin: "ài hào", meaning: "งานอดิเรก" },
  { chinese: "八", pinyin: "bā", meaning: "แปด" },
  { chinese: "爸爸", pinyin: "bà ba", meaning: "พ่อ" },
  { chinese: "爸", pinyin: "bà", meaning: "พ่อ" },
  { chinese: "吧", pinyin: "ba", meaning: "คำช่วยแสดงการขอร้อง/แนะนำ" },
  { chinese: "白", pinyin: "bái", meaning: "ขาว" },
  { chinese: "白天", pinyin: "bái tiān", meaning: "กลางวัน" },
  { chinese: "百", pinyin: "bǎi", meaning: "ร้อย" },
  { chinese: "班", pinyin: "bān", meaning: "ห้องเรียน, กลุ่ม" },
  { chinese: "半", pinyin: "bàn", meaning: "ครึ่ง" },
  { chinese: "半年", pinyin: "bàn nián", meaning: "ครึ่งปี" },
  { chinese: "半天", pinyin: "bàn tiān", meaning: "ครึ่งวัน" },
  { chinese: "帮", pinyin: "bāng", meaning: "ช่วย" },
  { chinese: "帮忙", pinyin: "bāng máng", meaning: "ช่วยเหลือ" },
  { chinese: "包", pinyin: "bāo", meaning: "ห่อ, ซอง" },
  { chinese: "包子", pinyin: "bāo zi", meaning: "ซาลาเปา" },
  { chinese: "杯", pinyin: "bēi", meaning: "แก้ว" },
  { chinese: "杯子", pinyin: "bēi zi", meaning: "แก้วน้ำ" },
  { chinese: "北", pinyin: "běi", meaning: "เหนือ" },
  { chinese: "北边", pinyin: "běi biān", meaning: "ด้านเหนือ" },
  { chinese: "北京", pinyin: "běi jīng", meaning: "ปักกิ่ง" },
  { chinese: "本", pinyin: "běn", meaning: "เล่ม (ลักษณนาม)" },
  { chinese: "本子", pinyin: "běn zi", meaning: "สมุด" },
  { chinese: "比", pinyin: "bǐ", meaning: "กว่า (ใช้เปรียบเทียบ)" },
  { chinese: "别", pinyin: "bié", meaning: "อย่า" },
  { chinese: "别的", pinyin: "bié de", meaning: "อื่น ๆ" },
  { chinese: "别人", pinyin: "bié rén", meaning: "คนอื่น" },
  { chinese: "病", pinyin: "bìng", meaning: "โรค, เจ็บป่วย" },
  { chinese: "病人", pinyin: "bìng rén", meaning: "คนไข้" },
  { chinese: "不大", pinyin: "bú dà", meaning: "ไม่ใหญ่" },
  { chinese: "不对", pinyin: "bú duì", meaning: "ผิด" },
  { chinese: "不客气", pinyin: "bú kè qì", meaning: "ไม่เป็นไร, ยินดี" },
  { chinese: "不用", pinyin: "bú yòng", meaning: "ไม่ต้อง" },
  { chinese: "不", pinyin: "bù", meaning: "ไม่" },
  { chinese: "菜", pinyin: "cài", meaning: "กับข้าว" },
  { chinese: "茶", pinyin: "chá", meaning: "ชา" },
  { chinese: "差", pinyin: "chà", meaning: "แย่, ขาด" },
  { chinese: "常", pinyin: "cháng", meaning: "บ่อย" },
  { chinese: "常常", pinyin: "cháng cháng", meaning: "บ่อยครั้ง" },
  { chinese: "唱", pinyin: "chàng", meaning: "ร้องเพลง" },
  { chinese: "唱歌", pinyin: "chàng gē", meaning: "ร้องเพลง" },
  { chinese: "车", pinyin: "chē", meaning: "รถ" },
  { chinese: "车票", pinyin: "chē piào", meaning: "ตั๋วรถ" },
  { chinese: "车上", pinyin: "chē shàng", meaning: "บนรถ" },
  { chinese: "车站", pinyin: "chē zhàn", meaning: "สถานีรถ" },
  { chinese: "吃", pinyin: "chī", meaning: "กิน" },
  { chinese: "吃饭", pinyin: "chī fàn", meaning: "กินข้าว" },
  { chinese: "出", pinyin: "chū", meaning: "ออก" },
  { chinese: "出来", pinyin: "chū lái", meaning: "ออกมา" },
  { chinese: "出去", pinyin: "chū qù", meaning: "ออกไป" },
  { chinese: "穿", pinyin: "chuān", meaning: "ใส่ (เสื้อผ้า)" },
  { chinese: "床", pinyin: "chuáng", meaning: "เตียง" },
  { chinese: "次", pinyin: "cì", meaning: "ครั้ง (ลักษณนาม)" },
  { chinese: "从", pinyin: "cóng", meaning: "จาก" },
  { chinese: "错", pinyin: "cuò", meaning: "ผิด" },
  { chinese: "打", pinyin: "dǎ", meaning: "ตี, โทร" },
  { chinese: "打车", pinyin: "dǎ chē", meaning: "เรียกแท็กซี่" },
  { chinese: "打电话", pinyin: "dǎ diàn huà", meaning: "โทรศัพท์" },
  { chinese: "打开", pinyin: "dǎ kāi", meaning: "เปิด" },
  { chinese: "打球", pinyin: "dǎ qiú", meaning: "เล่นบอล" },
  { chinese: "大", pinyin: "dà", meaning: "ใหญ่" },
  { chinese: "大学", pinyin: "dà xué", meaning: "มหาวิทยาลัย" },
  { chinese: "大学生", pinyin: "dà xué shēng", meaning: "นักศึกษามหาวิทยาลัย" },
  { chinese: "到", pinyin: "dào", meaning: "ถึง" },
  { chinese: "得到", pinyin: "dé dào", meaning: "ได้มา" },
  { chinese: "地", pinyin: "de", meaning: "คำช่วย (กริยาวิเศษณ์)" },
  { chinese: "的", pinyin: "de", meaning: "คำช่วย (แสดงความเป็นเจ้าของ)" },
  { chinese: "等", pinyin: "děng", meaning: "รอ" },
  { chinese: "地", pinyin: "dì", meaning: "พื้นดิน" },
  { chinese: "地点", pinyin: "dì diǎn", meaning: "สถานที่" },
  { chinese: "地方", pinyin: "dì fāng", meaning: "ท้องถิ่น" },
  { chinese: "地上", pinyin: "dì shàng", meaning: "บนพื้น" },
  { chinese: "地图", pinyin: "dì tú", meaning: "แผนที่" },
  { chinese: "弟弟", pinyin: "dì di", meaning: "น้องชาย" },
  { chinese: "弟", pinyin: "dì", meaning: "น้องชาย" },
  { chinese: "第二", pinyin: "dì èr", meaning: "ที่สอง" },
  { chinese: "点", pinyin: "diǎn", meaning: "จุด, นาฬิกา" },
  { chinese: "电", pinyin: "diàn", meaning: "ไฟฟ้า" },
  { chinese: "电话", pinyin: "diàn huà", meaning: "โทรศัพท์" },
  { chinese: "电脑", pinyin: "diàn nǎo", meaning: "คอมพิวเตอร์" },
  { chinese: "电视", pinyin: "diàn shì", meaning: "โทรทัศน์" },
  { chinese: "电视机", pinyin: "diàn shì jī", meaning: "เครื่องโทรทัศน์" },
  { chinese: "电影", pinyin: "diàn yǐng", meaning: "ภาพยนตร์" },
  { chinese: "电影院", pinyin: "diàn yǐng yuàn", meaning: "โรงภาพยนตร์" },
  { chinese: "东", pinyin: "dōng", meaning: "ตะวันออก" },
  { chinese: "东边", pinyin: "dōng biān", meaning: "ด้านตะวันออก" },
  { chinese: "东西", pinyin: "dōng xi", meaning: "สิ่งของ" },
  { chinese: "动", pinyin: "dòng", meaning: "เคลื่อนไหว" },
  { chinese: "动作", pinyin: "dòng zuò", meaning: "การกระทำ" },
  { chinese: "都", pinyin: "dōu", meaning: "ทั้งหมด" },
  { chinese: "读", pinyin: "dú", meaning: "อ่าน" },
  { chinese: "读书", pinyin: "dú shū", meaning: "อ่านหนังสือ, เรียน" },
  { chinese: "对", pinyin: "duì", meaning: "ถูกต้อง" },
  { chinese: "对不起", pinyin: "duì bu qǐ", meaning: "ขอโทษ" },
  { chinese: "多", pinyin: "duō", meaning: "มาก" },
  { chinese: "多少", pinyin: "duō shǎo", meaning: "เท่าไหร่" },
  { chinese: "饿", pinyin: "è", meaning: "หิว" },
  { chinese: "儿子", pinyin: "ér zi", meaning: "ลูกชาย" },
  { chinese: "二", pinyin: "èr", meaning: "สอง" },
  { chinese: "饭", pinyin: "fàn", meaning: "ข้าว, อาหาร" },
  { chinese: "饭店", pinyin: "fàn diàn", meaning: "ร้านอาหาร" },
  { chinese: "房间", pinyin: "fáng jiān", meaning: "ห้อง" },
  { chinese: "房子", pinyin: "fáng zi", meaning: "บ้าน" },
  { chinese: "放", pinyin: "fàng", meaning: "วาง" },
  { chinese: "放假", pinyin: "fàng jià", meaning: "หยุดวันหยุด" },
  { chinese: "放学", pinyin: "fàng xué", meaning: "เลิกเรียน" },
  { chinese: "飞", pinyin: "fēi", meaning: "บิน" },
  { chinese: "飞机", pinyin: "fēi jī", meaning: "เครื่องบิน" },
  { chinese: "非常", pinyin: "fēi cháng", meaning: "มาก" },
  { chinese: "分", pinyin: "fēn", meaning: "นาที" },
  { chinese: "风", pinyin: "fēng", meaning: "ลม" },
  { chinese: "干", pinyin: "gān", meaning: "แห้ง" },
  { chinese: "干净", pinyin: "gān jìng", meaning: "สะอาด" },
  { chinese: "干", pinyin: "gàn", meaning: "ทำ" },
  { chinese: "干什么", pinyin: "gàn shén me", meaning: "ทำอะไร" },
  { chinese: "高", pinyin: "gāo", meaning: "สูง" },
  { chinese: "高兴", pinyin: "gāo xìng", meaning: "มีความสุข" },
  { chinese: "告诉", pinyin: "gào su", meaning: "บอก" },
  { chinese: "哥哥", pinyin: "gē ge", meaning: "พี่ชาย" },
  { chinese: "哥", pinyin: "gē", meaning: "พี่ชาย" },
  { chinese: "歌", pinyin: "gē", meaning: "เพลง" },
  { chinese: "个", pinyin: "gè", meaning: "อัน (ลักษณนาม)" },
  { chinese: "给", pinyin: "gěi", meaning: "ให้" },
  { chinese: "跟", pinyin: "gēn", meaning: "กับ" },
  { chinese: "工人", pinyin: "gōng rén", meaning: "กรรมกร" },
  { chinese: "工作", pinyin: "gōng zuò", meaning: "ทำงาน" },
  { chinese: "关", pinyin: "guān", meaning: "ปิด" },
  { chinese: "关上", pinyin: "guān shàng", meaning: "ปิด" },
  { chinese: "贵", pinyin: "guì", meaning: "แพง" },
  { chinese: "国", pinyin: "guó", meaning: "ประเทศ" },
  { chinese: "国家", pinyin: "guó jiā", meaning: "ประเทศ" },
  { chinese: "国外", pinyin: "guó wài", meaning: "ต่างประเทศ" },
  { chinese: "过", pinyin: "guò", meaning: "ผ่าน" },
  { chinese: "还", pinyin: "hái", meaning: "ยัง" },
  { chinese: "还是", pinyin: "hái shi", meaning: "ยัง" },
  { chinese: "还有", pinyin: "hái yǒu", meaning: "นอกจากนี้" },
  { chinese: "孩子", pinyin: "hái zi", meaning: "เด็ก" },
  { chinese: "汉语", pinyin: "hàn yǔ", meaning: "ภาษาจีน" },
  { chinese: "汉字", pinyin: "hàn zì", meaning: "อักษรจีน" },
  { chinese: "好", pinyin: "hǎo", meaning: "ดี" },
  { chinese: "好吃", pinyin: "hǎo chī", meaning: "อร่อย" },
  { chinese: "好看", pinyin: "hǎo kàn", meaning: "สวย" },
  { chinese: "好听", pinyin: "hǎo tīng", meaning: "ฟังเพราะ" },
  { chinese: "好玩儿", pinyin: "hǎo wán er", meaning: "สนุก" },
  { chinese: "号", pinyin: "hào", meaning: "วันที่" },
  { chinese: "喝", pinyin: "hē", meaning: "ดื่ม" },
  { chinese: "和", pinyin: "hé", meaning: "และ" },
  { chinese: "很", pinyin: "hěn", meaning: "มาก" },
  { chinese: "后", pinyin: "hòu", meaning: "หลัง" },
  { chinese: "后边", pinyin: "hòu biān", meaning: "ด้านหลัง" },
  { chinese: "后天", pinyin: "hòu tiān", meaning: "มะรืนนี้" },
  { chinese: "花", pinyin: "huā", meaning: "ดอกไม้" },
  { chinese: "话", pinyin: "huà", meaning: "คำพูด" },
  { chinese: "坏", pinyin: "huài", meaning: "ไม่ดี" },
  { chinese: "还", pinyin: "huán", meaning: "คืน" },
  { chinese: "回", pinyin: "huí", meaning: "กลับ" },
  { chinese: "回答", pinyin: "huí dá", meaning: "ตอบ" },
  { chinese: "回到", pinyin: "huí dào", meaning: "กลับไปยัง" },
  { chinese: "回家", pinyin: "huí jiā", meaning: "กลับบ้าน" },
  { chinese: "回来", pinyin: "huí lái", meaning: "กลับมา" },
  { chinese: "回去", pinyin: "huí qù", meaning: "กลับไป" },
  { chinese: "会", pinyin: "huì", meaning: "สามารถ" },
  { chinese: "火车", pinyin: "huǒ chē", meaning: "รถไฟ" },
  { chinese: "机场", pinyin: "jī chǎng", meaning: "สนามบิน" },
  { chinese: "机票", pinyin: "jī piào", meaning: "ตั๋วเครื่องบิน" },
  { chinese: "鸡蛋", pinyin: "jī dàn", meaning: "ไข่ไก่" },
  { chinese: "几", pinyin: "jǐ", meaning: "กี่" },
  { chinese: "记", pinyin: "jì", meaning: "จำ" },
  { chinese: "记得", pinyin: "jì de", meaning: "จำได้" },
  { chinese: "记住", pinyin: "jì zhù", meaning: "จำไว้" },
  { chinese: "家", pinyin: "jiā", meaning: "บ้าน" },
  { chinese: "家里", pinyin: "jiā lǐ", meaning: "ในบ้าน" },
  { chinese: "家人", pinyin: "jiā rén", meaning: "คนในครอบครัว" },
  { chinese: "间", pinyin: "jiān", meaning: "ห้อง (ลักษณนาม)" },
  { chinese: "见", pinyin: "jiàn", meaning: "เห็น, เจอ" },
  { chinese: "见面", pinyin: "jiàn miàn", meaning: "เจอกัน" },
  { chinese: "教", pinyin: "jiāo", meaning: "สอน" },
  { chinese: "叫", pinyin: "jiào", meaning: "เรียก, ชื่อ" },
  { chinese: "教学楼", pinyin: "jiào xué lóu", meaning: "อาคารเรียน" },
  { chinese: "姐姐", pinyin: "jiě jie", meaning: "พี่สาว" },
  { chinese: "姐", pinyin: "jiě", meaning: "พี่สาว" },
  { chinese: "介绍", pinyin: "jiè shào", meaning: "แนะนำ" },
  { chinese: "今年", pinyin: "jīn nián", meaning: "ปีนี้" },
  { chinese: "今天", pinyin: "jīn tiān", meaning: "วันนี้" },
  { chinese: "进", pinyin: "jìn", meaning: "เข้า" },
  { chinese: "进来", pinyin: "jìn lái", meaning: "เข้ามา" },
  { chinese: "进去", pinyin: "jìn qù", meaning: "เข้าไป" },
  { chinese: "九", pinyin: "jiǔ", meaning: "เก้า" },
  { chinese: "就", pinyin: "jiù", meaning: "ก็ (ทันที)" },
  { chinese: "觉得", pinyin: "jué de", meaning: "รู้สึก" },
  { chinese: "开", pinyin: "kāi", meaning: "เปิด" },
  { chinese: "开车", pinyin: "kāi chē", meaning: "ขับรถ" },
  { chinese: "开会", pinyin: "kāi huì", meaning: "ประชุม" },
  { chinese: "开玩笑", pinyin: "kāi wán xiào", meaning: "ล้อเล่น" },
  { chinese: "看", pinyin: "kàn", meaning: "ดู" },
  { chinese: "看病", pinyin: "kàn bìng", meaning: "หาหมอ" },
  { chinese: "看到", pinyin: "kàn dào", meaning: "เห็น" },
  { chinese: "看见", pinyin: "kàn jiàn", meaning: "เห็น" },
  { chinese: "考", pinyin: "kǎo", meaning: "สอบ" },
  { chinese: "考试", pinyin: "kǎo shì", meaning: "การสอบ" },
  { chinese: "渴", pinyin: "kě", meaning: "กระหาย" },
  { chinese: "课", pinyin: "kè", meaning: "วิชา" },
  { chinese: "课本", pinyin: "kè běn", meaning: "หนังสือเรียน" },
  { chinese: "课文", pinyin: "kè wén", meaning: "บทเรียน" },
  { chinese: "口", pinyin: "kǒu", meaning: "ปาก" },
  { chinese: "块", pinyin: "kuài", meaning: "ก้อน" },
  { chinese: "快", pinyin: "kuài", meaning: "เร็ว" },
  { chinese: "来", pinyin: "lái", meaning: "มา" },
  { chinese: "来到", pinyin: "lái dào", meaning: "มาถึง" },
  { chinese: "老", pinyin: "lǎo", meaning: "แก่" },
  { chinese: "老人", pinyin: "lǎo rén", meaning: "คนแก่" },
  { chinese: "老师", pinyin: "lǎo shī", meaning: "ครู" },
  { chinese: "了", pinyin: "le", meaning: "แล้ว (แสดงอดีต)" },
  { chinese: "累", pinyin: "lèi", meaning: "เหนื่อย" },
  { chinese: "冷", pinyin: "lěng", meaning: "หนาว" },
  { chinese: "里", pinyin: "lǐ", meaning: "ข้างใน" },
  { chinese: "里边", pinyin: "lǐ biān", meaning: "ข้างใน" },
  { chinese: "两", pinyin: "liǎng", meaning: "สอง" },
  { chinese: "零", pinyin: "líng", meaning: "ศูนย์" },
  { chinese: "六", pinyin: "liù", meaning: "หก" },
  { chinese: "楼", pinyin: "lóu", meaning: "ชั้น" },
  { chinese: "楼上", pinyin: "lóu shàng", meaning: "ชั้นบน" },
  { chinese: "楼下", pinyin: "lóu xià", meaning: "ชั้นล่าง" },
  { chinese: "路", pinyin: "lù", meaning: "ถนน" },
  { chinese: "路口", pinyin: "lù kǒu", meaning: "ทางแยก" },
  { chinese: "路上", pinyin: "lù shàng", meaning: "บนถนน" },
  { chinese: "妈妈", pinyin: "mā ma", meaning: "แม่" },
  { chinese: "妈", pinyin: "mā", meaning: "แม่" },
  { chinese: "马路", pinyin: "mǎ lù", meaning: "ถนน" },
  { chinese: "马上", pinyin: "mǎ shàng", meaning: "ทันที" },
  { chinese: "吗", pinyin: "ma", meaning: "ไหม (คำถาม)" },
  { chinese: "买", pinyin: "mǎi", meaning: "ซื้อ" },
  { chinese: "慢", pinyin: "màn", meaning: "ช้า" },
  { chinese: "忙", pinyin: "máng", meaning: "ยุ่ง" },
  { chinese: "毛", pinyin: "máo", meaning: "เหมา (สกุลเงิน)" },
  { chinese: "没", pinyin: "méi", meaning: "ไม่มี" },
  { chinese: "没关系", pinyin: "méi guān xi", meaning: "ไม่เป็นไร" },
  { chinese: "没什么", pinyin: "méi shén me", meaning: "ไม่มีอะไร" },
  { chinese: "没事儿", pinyin: "méi shì er", meaning: "ไม่เป็นไร" },
  { chinese: "没有", pinyin: "méi yǒu", meaning: "ไม่มี" },
  { chinese: "妹妹", pinyin: "mèi mei", meaning: "น้องสาว" },
  { chinese: "妹", pinyin: "mèi", meaning: "น้องสาว" },
  { chinese: "门", pinyin: "mén", meaning: "ประตู" },
  { chinese: "门口", pinyin: "mén kǒu", meaning: "หน้าประตู" },
  { chinese: "门票", pinyin: "mén piào", meaning: "ตั๋วเข้าชม" },
  { chinese: "们", pinyin: "men", meaning: "พวก (พหูพจน์)" },
  { chinese: "米饭", pinyin: "mǐ fàn", meaning: "ข้าวสวย" },
  { chinese: "面包", pinyin: "miàn bāo", meaning: "ขนมปัง" },
  { chinese: "面条儿", pinyin: "miàn tiáo er", meaning: "บะหมี่" },
  { chinese: "名字", pinyin: "míng zi", meaning: "ชื่อ" },
  { chinese: "明白", pinyin: "míng bai", meaning: "เข้าใจ" },
  { chinese: "明年", pinyin: "míng nián", meaning: "ปีหน้า" },
  { chinese: "明天", pinyin: "míng tiān", meaning: "พรุ่งนี้" },
  { chinese: "拿", pinyin: "ná", meaning: "ถือ" },
  { chinese: "哪", pinyin: "nǎ", meaning: "ไหน" },
  { chinese: "哪里", pinyin: "nǎ lǐ", meaning: "ที่ไหน" },
  { chinese: "哪儿", pinyin: "nǎ er", meaning: "ที่ไหน" },
  { chinese: "哪些", pinyin: "nǎ xiē", meaning: "ไหนบ้าง" },
  { chinese: "那", pinyin: "nà", meaning: "นั่น" },
  { chinese: "那边", pinyin: "nà biān", meaning: "ด้านนั้น" },
  { chinese: "那里", pinyin: "nà lǐ", meaning: "ที่นั่น" },
  { chinese: "那儿", pinyin: "nà er", meaning: "ที่นั่น" },
  { chinese: "那些", pinyin: "nà xiē", meaning: "เหล่านั้น" },
  { chinese: "奶", pinyin: "nǎi", meaning: "นม" },
  { chinese: "奶奶", pinyin: "nǎi nai", meaning: "ยาย" },
  { chinese: "男", pinyin: "nán", meaning: "ผู้ชาย" },
  { chinese: "男孩儿", pinyin: "nán hái er", meaning: "เด็กผู้ชาย" },
  { chinese: "男朋友", pinyin: "nán péng yǒu", meaning: "แฟนหนุ่ม" },
  { chinese: "男人", pinyin: "nán rén", meaning: "ผู้ชาย" },
  { chinese: "男生", pinyin: "nán shēng", meaning: "นักเรียนชาย" },
  { chinese: "南", pinyin: "nán", meaning: "ใต้" },
  { chinese: "南边", pinyin: "nán biān", meaning: "ด้านใต้" },
  { chinese: "难", pinyin: "nán", meaning: "ยาก" },
  { chinese: "呢", pinyin: "ne", meaning: "ล่ะ (คำถาม)" },
  { chinese: "能", pinyin: "néng", meaning: "สามารถ" },
  { chinese: "你", pinyin: "nǐ", meaning: "คุณ" },
  { chinese: "你们", pinyin: "nǐ men", meaning: "พวกคุณ" },
  { chinese: "年", pinyin: "nián", meaning: "ปี" },
  { chinese: "您", pinyin: "nín", meaning: "คุณ (สุภาพ)" },
  { chinese: "牛奶", pinyin: "niú nǎi", meaning: "นมวัว" },
  { chinese: "女", pinyin: "nǚ", meaning: "ผู้หญิง" },
  { chinese: "女儿", pinyin: "nǚ ér", meaning: "ลูกสาว" },
  { chinese: "女孩儿", pinyin: "nǚ hái er", meaning: "เด็กผู้หญิง" },
  { chinese: "女朋友", pinyin: "nǚ péng yǒu", meaning: "แฟนสาว" },
  { chinese: "女人", pinyin: "nǚ rén", meaning: "ผู้หญิง" },
  { chinese: "女生", pinyin: "nǚ shēng", meaning: "นักเรียนหญิง" },
  { chinese: "旁边", pinyin: "páng biān", meaning: "ข้างๆ" },
  { chinese: "跑", pinyin: "pǎo", meaning: "วิ่ง" },
  { chinese: "朋友", pinyin: "péng you", meaning: "เพื่อน" },
  { chinese: "票", pinyin: "piào", meaning: "ตั๋ว" },
  { chinese: "七", pinyin: "qī", meaning: "เจ็ด" },
  { chinese: "起", pinyin: "qǐ", meaning: "ลุก" },
  { chinese: "起床", pinyin: "qǐ chuáng", meaning: "ตื่นนอน" },
  { chinese: "起来", pinyin: "qǐ lái", meaning: "ลุกขึ้น" },
  { chinese: "汽车", pinyin: "qì chē", meaning: "รถยนต์" },
  { chinese: "前", pinyin: "qián", meaning: "หน้า" },
  { chinese: "前边", pinyin: "qián biān", meaning: "ด้านหน้า" },
  { chinese: "前天", pinyin: "qián tiān", meaning: "เมื่อวานซืน" },
  { chinese: "钱", pinyin: "qián", meaning: "เงิน" },
  { chinese: "钱包", pinyin: "qián bāo", meaning: "กระเป๋าเงิน" },
  { chinese: "请", pinyin: "qǐng", meaning: "กรุณา" },
  { chinese: "请假", pinyin: "qǐng jià", meaning: "ลาหยุด" },
  { chinese: "请进", pinyin: "qǐng jìn", meaning: "เชิญเข้า" },
  { chinese: "请问", pinyin: "qǐng wèn", meaning: "ขอถามหน่อย" },
  { chinese: "请坐", pinyin: "qǐng zuò", meaning: "เชิญนั่ง" },
  { chinese: "球", pinyin: "qiú", meaning: "ลูกบอล" },
  { chinese: "去", pinyin: "qù", meaning: "ไป" },
  { chinese: "去年", pinyin: "qù nián", meaning: "ปีที่แล้ว" },
  { chinese: "热", pinyin: "rè", meaning: "ร้อน" },
  { chinese: "人", pinyin: "rén", meaning: "คน" },
  { chinese: "认识", pinyin: "rèn shi", meaning: "รู้จัก" },
  { chinese: "认真", pinyin: "rèn zhēn", meaning: "จริงจัง" },
  { chinese: "日", pinyin: "rì", meaning: "วัน" },
  { chinese: "日期", pinyin: "rì qī", meaning: "วันที่" },
  { chinese: "肉", pinyin: "ròu", meaning: "เนื้อ" },
  { chinese: "三", pinyin: "sān", meaning: "สาม" },
  { chinese: "山", pinyin: "shān", meaning: "ภูเขา" },
  { chinese: "商场", pinyin: "shāng chǎng", meaning: "ห้างสรรพสินค้า" },
  { chinese: "商店", pinyin: "shāng diàn", meaning: "ร้านค้า" },
  { chinese: "上", pinyin: "shàng", meaning: "บน" },
  { chinese: "上班", pinyin: "shàng bān", meaning: "ไปทำงาน" },
  { chinese: "上边", pinyin: "shàng biān", meaning: "ด้านบน" },
  { chinese: "上车", pinyin: "shàng chē", meaning: "ขึ้นรถ" },
  { chinese: "上次", pinyin: "shàng cì", meaning: "ครั้งที่แล้ว" },
  { chinese: "上课", pinyin: "shàng kè", meaning: "เข้าชั้นเรียน" },
  { chinese: "上网", pinyin: "shàng wǎng", meaning: "ใช้อินเทอร์เน็ต" },
  { chinese: "上午", pinyin: "shàng wǔ", meaning: "ตอนเช้า" },
  { chinese: "上学", pinyin: "shàng xué", meaning: "ไปโรงเรียน" },
  { chinese: "少", pinyin: "shǎo", meaning: "น้อย" },
  { chinese: "谁", pinyin: "shéi", meaning: "ใคร" },
  { chinese: "身上", pinyin: "shēn shàng", meaning: "บนตัว" },
  { chinese: "身体", pinyin: "shēn tǐ", meaning: "ร่างกาย" },
  { chinese: "什么", pinyin: "shén me", meaning: "อะไร" },
  { chinese: "生病", pinyin: "shēng bìng", meaning: "ป่วย" },
  { chinese: "生气", pinyin: "shēng qì", meaning: "โกรธ" },
  { chinese: "生日", pinyin: "shēng rì", meaning: "วันเกิด" },
  { chinese: "十", pinyin: "shí", meaning: "สิบ" },
  { chinese: "时候", pinyin: "shí hou", meaning: "เวลา" },
  { chinese: "时间", pinyin: "shí jiān", meaning: "เวลา" },
  { chinese: "事", pinyin: "shì", meaning: "เรื่อง" },
  { chinese: "试", pinyin: "shì", meaning: "ลอง" },
  { chinese: "是", pinyin: "shì", meaning: "ใช่" },
  { chinese: "是不是", pinyin: "shì bú shì", meaning: "ใช่ไหม" },
  { chinese: "手", pinyin: "shǒu", meaning: "มือ" },
  { chinese: "手机", pinyin: "shǒu jī", meaning: "มือถือ" },
  { chinese: "书", pinyin: "shū", meaning: "หนังสือ" },
  { chinese: "书包", pinyin: "shū bāo", meaning: "กระเป๋านักเรียน" },
  { chinese: "书店", pinyin: "shū diàn", meaning: "ร้านหนังสือ" },
  { chinese: "树", pinyin: "shù", meaning: "ต้นไม้" },
  { chinese: "水", pinyin: "shuǐ", meaning: "น้ำ" },
  { chinese: "水果", pinyin: "shuǐ guǒ", meaning: "ผลไม้" },
  { chinese: "睡", pinyin: "shuì", meaning: "นอน" },
  { chinese: "睡觉", pinyin: "shuì jiào", meaning: "นอนหลับ" },
  { chinese: "说", pinyin: "shuō", meaning: "พูด" },
  { chinese: "说话", pinyin: "shuō huà", meaning: "พูดคุย" },
  { chinese: "四", pinyin: "sì", meaning: "สี่" },
  { chinese: "送", pinyin: "sòng", meaning: "ให้" },
  { chinese: "岁", pinyin: "suì", meaning: "ปี (อายุ)" },
  { chinese: "他", pinyin: "tā", meaning: "เขา (ผู้ชาย)" },
  { chinese: "他们", pinyin: "tā men", meaning: "พวกเขา" },
  { chinese: "她", pinyin: "tā", meaning: "เขา (ผู้หญิง)" },
  { chinese: "她们", pinyin: "tā men", meaning: "พวกเธอ" },
  { chinese: "太", pinyin: "tài", meaning: "เกินไป" },
  { chinese: "天", pinyin: "tiān", meaning: "วัน, ท้องฟ้า" },
  { chinese: "天气", pinyin: "tiān qì", meaning: "สภาพอากาศ" },
  { chinese: "听", pinyin: "tīng", meaning: "ฟัง" },
  { chinese: "听到", pinyin: "tīng dào", meaning: "ได้ยิน" },
  { chinese: "听见", pinyin: "tīng jiàn", meaning: "ได้ยิน" },
  { chinese: "听写", pinyin: "tīng xiě", meaning: "เขียนตามคำบอก" },
  { chinese: "同学", pinyin: "tóng xué", meaning: "เพื่อนร่วมชั้น" },
  { chinese: "图书馆", pinyin: "tú shū guǎn", meaning: "ห้องสมุด" },
  { chinese: "外", pinyin: "wài", meaning: "ข้างนอก" },
  { chinese: "外边", pinyin: "wài biān", meaning: "ด้านนอก" },
  { chinese: "外国", pinyin: "wài guó", meaning: "ต่างประเทศ" },
  { chinese: "外语", pinyin: "wài yǔ", meaning: "ภาษาต่างประเทศ" },
  { chinese: "玩儿", pinyin: "wán er", meaning: "เล่น" },
  { chinese: "晚", pinyin: "wǎn", meaning: "สาย" },
  { chinese: "晚饭", pinyin: "wǎn fàn", meaning: "อาหารเย็น" },
  { chinese: "晚上", pinyin: "wǎn shang", meaning: "กลางคืน" },
  { chinese: "网上", pinyin: "wǎng shàng", meaning: "ออนไลน์" },
  { chinese: "网友", pinyin: "wǎng yǒu", meaning: "เพื่อนทางเน็ต" },
  { chinese: "忘", pinyin: "wàng", meaning: "ลืม" },
  { chinese: "忘记", pinyin: "wàng jì", meaning: "ลืม" },
  { chinese: "问", pinyin: "wèn", meaning: "ถาม" },
  { chinese: "我", pinyin: "wǒ", meaning: "ฉัน" },
  { chinese: "我们", pinyin: "wǒ men", meaning: "พวกเรา" },
  { chinese: "五", pinyin: "wǔ", meaning: "ห้า" },
  { chinese: "午饭", pinyin: "wǔ fàn", meaning: "อาหารกลางวัน" },
  { chinese: "西", pinyin: "xī", meaning: "ตะวันตก" },
  { chinese: "西边", pinyin: "xī biān", meaning: "ด้านตะวันตก" },
  { chinese: "洗", pinyin: "xǐ", meaning: "ล้าง" },
  { chinese: "洗手间", pinyin: "xǐ shǒu jiān", meaning: "ห้องน้ำ" },
  { chinese: "喜欢", pinyin: "xǐ huan", meaning: "ชอบ" },
  { chinese: "下", pinyin: "xià", meaning: "ล่าง" },
  { chinese: "下班", pinyin: "xià bān", meaning: "เลิกงาน" },
  { chinese: "下边", pinyin: "xià biān", meaning: "ด้านล่าง" },
  { chinese: "下车", pinyin: "xià chē", meaning: "ลงรถ" },
  { chinese: "下次", pinyin: "xià cì", meaning: "ครั้งหน้า" },
  { chinese: "下课", pinyin: "xià kè", meaning: "เลิกเรียน" },
  { chinese: "下午", pinyin: "xià wǔ", meaning: "ตอนบ่าย" },
  { chinese: "下雨", pinyin: "xià yǔ", meaning: "ฝนตก" },
  { chinese: "先", pinyin: "xiān", meaning: "ก่อน" },
  { chinese: "先生", pinyin: "xiān sheng", meaning: "คุณ (ผู้ชาย)" },
  { chinese: "现在", pinyin: "xiàn zài", meaning: "ตอนนี้" },
  { chinese: "想", pinyin: "xiǎng", meaning: "คิด" },
  { chinese: "小", pinyin: "xiǎo", meaning: "เล็ก" },
  { chinese: "小孩儿", pinyin: "xiǎo hái er", meaning: "เด็ก" },
  { chinese: "小姐", pinyin: "xiǎo jiě", meaning: "คุณ (ผู้หญิง)" },
  { chinese: "小朋友", pinyin: "xiǎo péng yǒu", meaning: "เด็ก" },
  { chinese: "小时", pinyin: "xiǎo shí", meaning: "ชั่วโมง" },
  { chinese: "小学", pinyin: "xiǎo xué", meaning: "ประถมศึกษา" },
  { chinese: "小学生", pinyin: "xiǎo xué shēng", meaning: "นักเรียนประถม" },
  { chinese: "笑", pinyin: "xiào", meaning: "หัวเราะ" },
  { chinese: "写", pinyin: "xiě", meaning: "เขียน" },
  { chinese: "谢谢", pinyin: "xiè xie", meaning: "ขอบคุณ" },
  { chinese: "新", pinyin: "xīn", meaning: "ใหม่" },
  { chinese: "新年", pinyin: "xīn nián", meaning: "ปีใหม่" },
  { chinese: "星期", pinyin: "xīng qī", meaning: "สัปดาห์" },
  { chinese: "星期日", pinyin: "xīng qī rì", meaning: "วันอาทิตย์" },
  { chinese: "星期天", pinyin: "xīng qī tiān", meaning: "วันอาทิตย์" },
  { chinese: "行", pinyin: "xíng", meaning: "ได้" },
  { chinese: "休息", pinyin: "xiū xi", meaning: "พักผ่อน" },
  { chinese: "学", pinyin: "xué", meaning: "เรียนรู้" },
  { chinese: "学生", pinyin: "xué sheng", meaning: "นักเรียน" },
  { chinese: "学习", pinyin: "xué xí", meaning: "ศึกษา" },
  { chinese: "学校", pinyin: "xué xiào", meaning: "โรงเรียน" },
  { chinese: "学院", pinyin: "xué yuàn", meaning: "วิทยาลัย" },
  { chinese: "要", pinyin: "yào", meaning: "ต้องการ" },
  { chinese: "爷爷", pinyin: "yé ye", meaning: "ปู่" },
  { chinese: "也", pinyin: "yě", meaning: "ก็" },
  { chinese: "页", pinyin: "yè", meaning: "หน้า" },
  { chinese: "一", pinyin: "yī", meaning: "หนึ่ง" },
  { chinese: "衣服", pinyin: "yī fu", meaning: "เสื้อผ้า" },
  { chinese: "医生", pinyin: "yī shēng", meaning: "หมอ" },
  { chinese: "医院", pinyin: "yī yuàn", meaning: "โรงพยาบาล" },
  { chinese: "一半", pinyin: "yí bàn", meaning: "ครึ่งหนึ่ง" },
  { chinese: "一会儿", pinyin: "yī huǐ er", meaning: "สักครู่" },
  { chinese: "一块儿", pinyin: "yí kuài er", meaning: "ด้วยกัน" },
  { chinese: "一下儿", pinyin: "yí xià r", meaning: "สักหน่อย" },
  { chinese: "一样", pinyin: "yí yàng", meaning: "เหมือนกัน" },
  { chinese: "一边", pinyin: "yī biān", meaning: "ด้านหนึ่ง" },
  { chinese: "一点儿", pinyin: "yī diǎn r", meaning: "นิดหน่อย" },
  { chinese: "一起", pinyin: "yì qǐ", meaning: "ด้วยกัน" },
  { chinese: "一些", pinyin: "yì xiē", meaning: "บางส่วน" },
  { chinese: "用", pinyin: "yòng", meaning: "ใช้" },
  { chinese: "有", pinyin: "yǒu", meaning: "มี" },
  { chinese: "有的", pinyin: "yǒu de", meaning: "บาง" },
  { chinese: "有名", pinyin: "yǒu míng", meaning: "มีชื่อเสียง" },
  { chinese: "有时候", pinyin: "yǒu shí hou", meaning: "บางครั้ง" },
  { chinese: "有时", pinyin: "yǒu shí", meaning: "บางครั้ง" },
  { chinese: "有一些", pinyin: "yǒu yì xiē", meaning: "มีบางส่วน" },
  { chinese: "有用", pinyin: "yǒu yòng", meaning: "มีประโยชน์" },
  { chinese: "右", pinyin: "yòu", meaning: "ขวา" },
  { chinese: "右边", pinyin: "yòu bian", meaning: "ด้านขวา" },
  { chinese: "雨", pinyin: "yǔ", meaning: "ฝน" },
  { chinese: "元", pinyin: "yuán", meaning: "หยวน" },
  { chinese: "远", pinyin: "yuǎn", meaning: "ไกล" },
  { chinese: "月", pinyin: "yuè", meaning: "เดือน" },
  { chinese: "再", pinyin: "zài", meaning: "อีก" },
  { chinese: "再见", pinyin: "zài jiàn", meaning: "ลาก่อน" },
  { chinese: "在", pinyin: "zài", meaning: "อยู่ที่" },
  { chinese: "在家", pinyin: "zài jiā", meaning: "อยู่บ้าน" },
  { chinese: "早", pinyin: "zǎo", meaning: "เช้า" },
  { chinese: "早饭", pinyin: "zǎo fàn", meaning: "อาหารเช้า" },
  { chinese: "早上", pinyin: "zǎo shang", meaning: "ตอนเช้า" },
  { chinese: "怎么", pinyin: "zěn me", meaning: "อย่างไร" },
  { chinese: "站", pinyin: "zhàn", meaning: "สถานี" },
  { chinese: "找", pinyin: "zhǎo", meaning: "หา" },
  { chinese: "找到", pinyin: "zhǎo dào", meaning: "เจอ" },
  { chinese: "这", pinyin: "zhè", meaning: "นี้" },
  { chinese: "这边", pinyin: "zhè biān", meaning: "ด้านนี้" },
  { chinese: "这里", pinyin: "zhè lǐ", meaning: "ที่นี่" },
  { chinese: "这儿", pinyin: "zhè er", meaning: "ที่นี่" },
  { chinese: "这些", pinyin: "zhè xiē", meaning: "เหล่านี้" },
  { chinese: "着", pinyin: "zhe", meaning: "กำลัง (แสดงภาวะ)" },
  { chinese: "真", pinyin: "zhēn", meaning: "จริง" },
  { chinese: "真的", pinyin: "zhēn de", meaning: "จริงๆ" },
  { chinese: "正", pinyin: "zhèng", meaning: "กำลัง" },
  { chinese: "正在", pinyin: "zhèng zài", meaning: "กำลัง" },
  { chinese: "知道", pinyin: "zhī dào", meaning: "รู้" },
  { chinese: "知识", pinyin: "zhī shi", meaning: "ความรู้" },
  { chinese: "中", pinyin: "zhōng", meaning: "กลาง" },
  { chinese: "中国", pinyin: "zhōng guó", meaning: "จีน" },
  { chinese: "中间", pinyin: "zhōng jiān", meaning: "ตรงกลาง" },
  { chinese: "中文", pinyin: "zhōng wén", meaning: "ภาษาจีน" },
  { chinese: "中午", pinyin: "zhōng wǔ", meaning: "เที่ยงวัน" },
  { chinese: "中学", pinyin: "zhōng xué", meaning: "มัธยมศึกษา" },
  { chinese: "中学生", pinyin: "zhōng xué shēng", meaning: "นักเรียนมัธยม" },
  { chinese: "重", pinyin: "zhòng", meaning: "หนัก" },
  { chinese: "重要", pinyin: "zhòng yào", meaning: "สำคัญ" },
  { chinese: "住", pinyin: "zhù", meaning: "อยู่" },
  { chinese: "准备", pinyin: "zhǔn bèi", meaning: "เตรียม" },
  { chinese: "桌子", pinyin: "zhuō zi", meaning: "โต๊ะ" },
  { chinese: "字", pinyin: "zì", meaning: "ตัวอักษร" },
  { chinese: "子", pinyin: "zi", meaning: "คำต่อท้าย" },
  { chinese: "走", pinyin: "zǒu", meaning: "เดิน" },
  { chinese: "走路", pinyin: "zǒu lù", meaning: "เดิน" },
  { chinese: "最", pinyin: "zuì", meaning: "ที่สุด" },
  { chinese: "最好", pinyin: "zuì hǎo", meaning: "ดีที่สุด" },
  { chinese: "最后", pinyin: "zuì hòu", meaning: "สุดท้าย" },
  { chinese: "昨天", pinyin: "zuó tiān", meaning: "เมื่อวาน" },
  { chinese: "左", pinyin: "zuǒ", meaning: "ซ้าย" },
  { chinese: "左边", pinyin: "zuǒ bian", meaning: "ด้านซ้าย" },
  { chinese: "坐", pinyin: "zuò", meaning: "นั่ง" },
  { chinese: "坐下", pinyin: "zuò xià", meaning: "นั่งลง" },
  { chinese: "做", pinyin: "zuò", meaning: "ทำ" }
];

export default vocabulary;